title : Course Site for Bush 631 -- Fall 2022
logo: /assets/hex.png
author :
  name : Rotem Dvir
  email : rdvir@tamu.edu
  github : rotemdvir
  twitter : nil
  feedburner : nil

markdown: kramdown

theme: jekyll-theme-minimal
